### ISSUE TITLE
Add wimboot support for GRUB2 EFI (GRUB2 linuxefi bzImage / UEFI binary check)

### ISSUE THREAD

**Issue by Sporesirius** [a1ive/grub#2]
Hello, this problem with GRUB2 EFI and wimboot has apparently been around a bit longer and there have also been countless discussions in the repective mailing lists but not really with a solution and because of that I wanted to understand why wimboot and GRUB2 not working with each other in EFI mode.
I don't know much about GRUB2 or wimboot (had them just patched a little bit) but i think because wimboot is a combined bzImage / UEFI Binary and GRUB2 EFI displays a Kernel too old at startup off wimboot that means GRUB2 EFI tries to start the wimboot binary as kernel and not as UEFI binary.

Well I've seen that this repo here is active and interested in extended features maybe someone here knows a solution or even has a patch/fix for that?

I think linuxefi need a check for the PE and MZ headers? https://firmware.intel.com/blog/linux-efi-boot-stub

Kind regards,
Sporesirius

**Comment by a1ive** [comment]
I'm not familiar with linux kernel, so maybe it will require a lot of work.
Actually, porting wimboot as a grub module should be a better solution, and someone has implemented this feature.
[grub2x64.zip](https://github.com/a1ive/grub/files/3038409/grub2x64.zip)
Here you can try it.
For example: 
`runudm @bcd=/test/bcd @boot.sdi=/test/boot.sdi @bootx64.efi=/test/bootx64.efi  @boot.wim=/test/win10.wim`
Unfortunately, the author refused to publish the source code.
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=373513

**Comment by Sporesirius** [comment]
> I'm not familiar with linux kernel, so maybe it will require a lot of work.

I don't know how complicated such a check would be.

> Actually, porting wimboot as a grub module should be a better solution, and someone has implemented this feature.

Yeah, a GRUB2 module would be the best.

> [grub2x64.zip](https://github.com/a1ive/grub/files/3038409/grub2x64.zip)
> Here you can try it.
> For example:
> `runudm @bcd=/test/bcd @boot.sdi=/test/boot.sdi @bootx64.efi=/test/bootx64.efi @boot.wim=/test/win10.wim`

Okay thanks, i'll take a look.

> Unfortunately, the author refused to publish the source code.
> http://bbs.wuyou.net/forum.php?mod=viewthread&tid=373513

:(

**Comment by a1ive** [comment]
I can't make the module work properly. I hope someone can help me.

**Comment by jamefane** [comment]
I think we should first try to port wimboot to grub2 bios and then to UEFI.

**Comment by a1ive** [comment]
> I think we should first try to port wimboot to grub2 bios and then to UEFI.

I don't know assembly languages. I would very appreciate it if you could help me.

**Comment by jamefane** [comment]
Hello,
I'm sorry, but I don't have much time to help.
Anyway isn't it easier to fix GRUB2 EFI to start wimboot EFI instead of porting wimboot?

**Comment by a1ive** [comment]
0ee7eb861e7e770152652c9df070e5d5ed65acf4 
801e63ffbd9c54be1d9926b4f6809d7a5352684e 
The "wimboot" module is working now. I've tested on VmWare & my PC.
a modified version of ipxe-wimboot is embeded in the module.
modified wimboot source code: https://github.com/a1ive/wimboot

**Comment by a1ive** [comment]
Useage:
```
wimboot [--gui] [--rawbcd] [--rawwim] [--pause] [--index=n] @:boot.wim:/path/to/test.wim @:bootmgfw.efi:/path/to/test.efi @:bcd:/path/to/bcd @:boot.sdi:/path/to/boot.sdi
   * params:
   *         --gui or -g  Display graphical boot messages.
   *         --rawbcd or -b Disable rewriting .exe to .efi in the BCD file.
   *         --rawwim or -w Disable patching the wim file.
   *         --pause or -p
   *         --index=n or -i n Use WIM image index n.
```

**Comment by steve6375** [comment]
Can extra files such as winpeshl.ini be inserted into X:\windows\system32  in the same way that can be done with iPXE wimboot ?

**Comment by a1ive** [comment]
> Can extra files such as winpeshl.ini be inserted into X:\windows\system32 in the same way that can be done with iPXE wimboot ? This would be essential if trying to directly boot from Windows Install ISOs for instance.

yes

**Comment by guimenez** [comment]
Please, can you help me how to make wimboot work in UEFI mode?
Thank you.

**Comment by steve6375** [comment]
See www.rmprepusb.com tutorial 145

**Comment by a1ive** [comment]
Download binary version for windows: https://github.com/aIive/builds
run build_grub.bat to build grubx64.efi.
create grub2 menu file /boot/grub/grub.cfg
add this to menu:
menuentry "wimboot" {
  wimboot @:bcd:/path/to/bcd @:boot.sdi:/path/to/boot.sdi @:bootmgfw.efi:/path/to/bootx64.efi @:boot.wim:/path/to/win10.wim
}

**Comment by guimenez** [comment]
Thank you.
I will try it in the weekend. 
Still can't boot floppy images in UEFI mode?
I have a program to test disks that work in dos mode and I can't find any that works in UEFI :(

**Comment by steve6375** [comment]
Dos , xp and other real mode os's that depend on a BIOS will never work under uefi !!!

**Comment by guimenez** [comment]
I was thinking that it can be emulated has a BIOS.
But I think it will be impossible. 
Let's hope that developers make HDD diagnostics tests with UEFI support. 
Thanks

**Comment by a1ive** [comment]
Why not boot a tiny linux kernel and emulate a BIOS machine through QEMU (KVM)?

**Comment by guimenez** [comment]
Does the QEMU will recognize the physical HDD from machine to make hdd diagnostics?

**Comment by guimenez** [comment]
> Download binary version for windows: https://github.com/aIive/builds
> run build_grub.bat to build grubx64.efi.
> create grub2 menu file /boot/grub/grub.cfg
> add this to menu:
> 
> ```
> menuentry "wimboot" {
>   wimboot @:bcd:/path/to/bcd @:boot.sdi:/path/to/boot.sdi @:bootmgfw.efi:/path/to/bootx64.efi @:boot.wim:/path/to/win10.wim
> }
> ```

I've compile the grubx64.efi and copy it to EFI/BOOT
but when i start my flashdrive it says "can't find command wimboot"
I'm missing something?
Thanks

**Comment by a1ive** [comment]
This should not happen.
You should rename it to "bootx64.efi" if there are no preloader or shim efi files.
Or you should rename and copy grubia32.efi to flash drive if the uefi firmware is 32bit.

**Comment by guimenez** [comment]
> This should not happen.
> You should rename it to "bootx64.efi" if there are no preloader or shim efi files.
> Or you should rename and copy grubia32.efi to flash drive if the uefi firmware is 32bit.

Ok, It's booting and it find the 4 files needed to boot but after loading to memory i'm getting Windows 0X0C000000F error :(

**Comment by steve6375** [comment]
Change the order so that  wim file is first, then bcd then sdi.

**Comment by guimenez** [comment]
> Change the order so that wim file is first, then bcd then sdi.

Amazing, works like a charm.
Only 2 question please:
- Can i boot with secure boot option? Or i need always to disable it in UEFI firmware.
- Is it possible to map to an ISO without extracting to get access to the 4 files?

Thank you once again.

**Comment by steve6375** [comment]
re. Secure Boot. You would have to use a Shim and MokManager which doesn't always work and also programs the target systems NVRAM. So basically I recommend always disable Secure Boot.
re. mapping ISO - yes, I already gave you tutorial for direct boot from ISO - See www.rmprepusb.com tutorial 145
https://www.rmprepusb.com/tutorials/145-grub2winiso

**Comment by neps4u** [comment]
> I'm not familiar with linux kernel, so maybe it will require a lot of work.
> Actually, porting wimboot as a grub module should be a better solution, and someone has implemented this feature.
> [grub2x64.zip](https://github.com/a1ive/grub/files/3038409/grub2x64.zip)
> Here you can try it.
> For example:
> `runudm @bcd=/test/bcd @boot.sdi=/test/boot.sdi @bootx64.efi=/test/bootx64.efi @boot.wim=/test/win10.wim`
> Unfortunately, the author refused to publish the source code.
> http://bbs.wuyou.net/forum.php?mod=viewthread&tid=373513

do the same but getting Windows 0X0C000000F error
tried steve6375 advice but still not succeed. if anyone knows proper code let me know. thanks

**Comment by steve6375** [comment]
0xC000000F usually means the BCD is not pointing to the correct path/file.

**Comment by neps4u** [comment]
> 0xC000000F usually means the BCD is not pointing to the correct path/file.

Thanks steve6375 for quick reply.  used default windows 10 bcd with custom 
path. any advice

**Comment by a1ive** [comment]
> > 0xC000000F usually means the BCD is not pointing to the correct path/file.
> 
> Thanks steve6375 for quick reply. used default windows 10 bcd with custom
> path. any advice

What configuration (grub.cfg and bcd)/commands did you use ?

**Comment by neps4u** [comment]
grub.cfg - 

menuentry "Win-PE" {
	wimboot @:boot.wim:/sources/boot.wim \
				@:bootmgfw.efi:/boot/bootx64.efi \
                @:bcd:/EFI/BOOT/bcd \
                @:boot.sdi:/boot/boot.sdi \
                
}

BCD-

![bcd](https://user-images.githubusercontent.com/19203541/71443271-160cb100-2732-11ea-8e19-bfd2919b76c9.JPG)

**Comment by Sporesirius** [comment]
Hello agian, @neps4u you can take a look at: https://github.com/Sporesirius/YAMS/blob/60fea72f6ce7b4d984d16325b9b950e9ae9fdda5/YAMS/grub/configs/windows_based/win-bootmgr.d/generic.cfg#L48
and https://github.com/Sporesirius/YAMS/blob/master/YAMS/Tools/WSL/wsl.bat.
Maybe this is helpful.

**Comment by neps4u** [comment]
> Hello again, @neps4u you can take a look at: https://github.com/Sporesirius/YAMS/blob/60fea72f6ce7b4d984d16325b9b950e9ae9fdda5/YAMS/grub/configs/windows_based/win-bootmgr.d/generic.cfg#L48
> and https://github.com/Sporesirius/YAMS/blob/master/YAMS/Tools/WSL/wsl.bat.
> Maybe this is helpful.

thanks for the reply.. doesn't work.. any other help appreciated. thanks

**Comment by a1ive** [comment]
> > Hello again, @neps4u you can take a look at: https://github.com/Sporesirius/YAMS/blob/60fea72f6ce7b4d984d16325b9b950e9ae9fdda5/YAMS/grub/configs/windows_based/win-bootmgr.d/generic.cfg#L48
> > and https://github.com/Sporesirius/YAMS/blob/master/YAMS/Tools/WSL/wsl.bat.
> > Maybe this is helpful.
> 
> thanks for the reply.. doesn't work.. any other help appreciated. thanks

I recommend using [wimboot-bcd](https://github.com/NiKiZe/wimboot-bcd) to create bcd.
