### ISSUE TITLE
Query: is partnew supported under UEFI?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#23]
Using partnew in grub4dos, it is possible to boot 99% of Linux LiveCD ISO files directly without needing any kernel cheat codes, etc.
Is partnew supported when UEFI-booting (MBR partitions)?
Also, is dd (writes/reads to USB) and blocklist supported under UEFI?

**Comment by a1ive** [comment]
yes, yes, yes.
'dd' is not stable, use with caution
