### ISSUE TITLE
query: dd command

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#25]
Is it possible to backup sector 0 to sector 60 say of the same hard disk using dd?

e.g.
`dd --if=(hd0) --of=(hd0) --bs=512 --count=1 --seek=60 --skip=0
`

![image](https://user-images.githubusercontent.com/1469350/73182375-e1b15980-4110-11ea-99cc-7e7f58b77e28.png)
![image](https://user-images.githubusercontent.com/1469350/73182939-dd397080-4111-11ea-9227-c9b38f9cb576.png)

**Comment by a1ive** [comment]
I can implement it but why sector 60?

**Comment by steve6375** [comment]
Easy2Boot uses .imgPTN files. These are images of a complete partition.
It uses partnew to replace the Ptn1 with this new image.
It uses sector 30 and 60 as backup sectors for the drive MBR first.

1. If LBA 30 is unused (if contains all same bytes or if last two bytes are disk signature 55 AA) then copy LBA0 to LBA30
2. If LBA 60 is unused (if contains all same bytes or if last two bytes are disk signature 55 AA) then copy LBA0 to LBA60
3. Run partnew to replace ptn1 with  xxx.imgPTN file.
4. If file extension is .imgptn23 then keep partitions 2 and 3 - otherwise remove partitions 2 and 3.
Now USB drive contains new partition 1 - e.g. FAT32 partition containing Microsoft Windows 10 and can be Secure UEFI-booted.


Now - to restore the original partitions:
1. Check LBA30 has disk signature in last two bytes - if so copy to LBA0, else repeat for LBA60.

So, I am looking for a way to copy disk sectors and also blank out bytes in disk sectors and also check the contents of disk sectors (e.g. check all 512 bytes are same value or check last two bytes 55 AA).

**Comment by steve6375** [comment]
Example:
Ptn1: NTFS containing multiple .imgPTN23 files
Ptn2: FAT32 containing a1ive grub2 File Manager

Now we can switch-in any .imgPTN23 file into partition 1 and UEFI-boot (or MBR-boot) to Ptn1.

**Comment by steve6375** [comment]
P.S. hexdump accepts (hd0)

![image](https://user-images.githubusercontent.com/1469350/73345120-6c15cc80-427b-11ea-998a-7d09386629b0.png)

**Comment by a1ive** [comment]
> P.S. hexdump accepts (hd0)
> 
> ![image](https://user-images.githubusercontent.com/1469350/73345120-6c15cc80-427b-11ea-998a-7d09386629b0.png)

We have grub_disk_read, grub_disk_write and grub_file_read, but no grub_file_write.That's the difference.

**Comment by steve6375** [comment]
OK
P.S. How can I test bytes (using hexdump) - e.g. last two bytes in a sector = 55 AA?

**Comment by a1ive** [comment]
I haven't found how to input or test hex data (\x[[:hex:]][[:hex:]])

**Comment by a1ive** [comment]
![深度截图_选择区域_20200129202637](https://user-images.githubusercontent.com/10670106/73411780-87e3a600-4341-11ea-9bcf-9b3cc08a179a.png)

**Comment by steve6375** [comment]
Thanks for hexdump mod - it is working.
Fixing dd of  --of=(hd0)30+1   etc would be VERY useful if it can be done... ;-)

**Comment by a1ive** [comment]
I haven't fully tested the module. Use with caution.
Writing to a file has not been implemented yet.
![深度截图_选择区域_20200201133132](https://user-images.githubusercontent.com/10670106/73588985-e27c2e00-450a-11ea-9017-9f31a2393feb.png)

**Comment by steve6375** [comment]
Looks great! I will test.
It is possible to use hexdump to get bytes into a variable and then use that variable to write into a sector using dd? The --hex= format does not look compatible with hexdump?

**Comment by steve6375** [comment]
Is (hd0)30+1 format also now supported for dd ?

**Comment by a1ive** [comment]
not implemented yet.
(hd0)30+1 is a file, not a disk.
maybe you could use --of=(hd0) --seek=xxx (30*512)?

**Comment by steve6375** [comment]
Seems to use a block size of 1 by default
![image](https://user-images.githubusercontent.com/1469350/73590167-44bb3b80-44d7-11ea-9141-0c7e1aa248b0.png)

**Comment by steve6375** [comment]
I am testing new dd and so far looking good 💯 

I still have the problem of not be able to run chainloader, etc.  even from partition 2 which has not been changed - but sometimes it will run from the menu. Any idea why it wont run?
![image](https://user-images.githubusercontent.com/1469350/73593206-5e6d7a80-44f9-11ea-99ef-2c7a9684938a.png)

**Comment by a1ive** [comment]
> It is possible to use hexdump to get bytes into a variable and then use that variable to write into a sector using dd? The --hex= format does not look compatible with hexdump?

It's possible, but why not use dd --if=file instead of hexdump?

**Comment by steve6375** [comment]
yes, I could just use dd, but just wondered how to convert one format to the other.

re. the chainloader issue


I have grub2 File Manager on 2nd FAT32 partition
ptn1: NTFS
ptn2: FAT32 with grub2 file manager

I add a \TEST.cfg file to  the 2nd FAT32 partition containing
	chainloader -b -t (hd0,msdos2)/EFI/Boot/bootx64.efi

Why wont this work ???

**Comment by a1ive** [comment]
> yes, I could just use dd, but just wondered how to convert one format to the other.
> 
> re. the chainloader issue
> 
> I have grub2 File Manager on 2nd FAT32 partition
> ptn1: NTFS
> ptn2: FAT32 with grub2 file manager
> 
> I add a \TEST.cfg file to the 2nd FAT32 partition containing
> chainloader -b -t (hd0,msdos2)/EFI/Boot/bootx64.efi
> 
> Why wont this work ???

you have not changed partition?
It's strange.What efi file did you use?

**Comment by steve6375** [comment]
I used the patch secure boot efi that you pointed me to.
it works if I use \grubfmx64.efi though - so i could use that.

**Comment by a1ive** [comment]
> I still have the problem of not be able to run chainloader, etc. even from partition 2 which has not been changed - but sometimes it will run from the menu. Any idea why it wont run?

Did you use dd on this drive before that?
There is a bug in the previous version of dd(ac7dccf), which will damage the data in other locations.

**Comment by a1ive** [comment]
> The --hex= format does not look compatible with hexdump?

--str="\x12\x34"
![深度截图_选择区域_20200202091702](https://user-images.githubusercontent.com/10670106/73604612-795dee80-45ce-11ea-802c-36741d3a2f3d.png)
But "\x00" doesn't work.
