### ISSUE TITLE
partnew is not compatible with grub4dos

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#26]
Test partition image attached
It is a 32MB FAT32 partition image.

If I use grub4dos to add this image in as a partition, the new partition can be seen in grub4dos, grub2 and Windows.

However, if I use the grub2 (in a1ive grub2 File Manager) to add in the same file using partnew, then although the new partition is accessible in grub2 and in Windows (if in correct order), grub4dos cannot see it!

It is very weird and I cannot see why grub4dos does not like it!

Ptn1: NTFS + grub4dos and \TESTFAT32.imgptn
Ptn2: FAT32 with grub2

If use grub4dos:
partnew (hd0,2) 0x0c /TESTFAT32.imptn
![image](https://user-images.githubusercontent.com/1469350/73358129-de93a600-4295-11ea-9f80-cf40f78a6a7e.png)
![image](https://user-images.githubusercontent.com/1469350/73358201-02ef8280-4296-11ea-9738-cf94c18637d8.png)

then new partition is accessible under grub4dos - all is good.

However, if I use grub2 to add the new partition:
  partnew --type=0x0C --file=(hd0,msdos1)/TESTFAT32.imgPTN (hd0) 3

![image](https://user-images.githubusercontent.com/1469350/73358307-3b8f5c00-4296-11ea-916e-07c2e2249d1b.png)

new partition can be accessed using grub2

and then reboot to grub4dos, grub4dos cannot see the new partition.

![image](https://user-images.githubusercontent.com/1469350/73358448-84471500-4296-11ea-875a-4e052282d627.png)

#####
[TESTFAT32.zip](https://github.com/a1ive/grub/files/4128073/TESTFAT32.zip)

**Comment by steve6375** [comment]
The difference seems to be in the partition table entries
[LBA0.zip](https://github.com/a1ive/grub/files/4128504/LBA0.zip)
![image](https://user-images.githubusercontent.com/1469350/73364784-11906680-42a3-11ea-9001-312c0958ffe8.png)
![image](https://user-images.githubusercontent.com/1469350/73364819-1fde8280-42a3-11ea-9805-28ac58b65180.png)

**Comment by a1ive** [comment]
> The difference seems to be in the partition table entries
> [LBA0.zip](https://github.com/a1ive/grub/files/4128504/LBA0.zip)
> ![image](https://user-images.githubusercontent.com/1469350/73364784-11906680-42a3-11ea-9001-312c0958ffe8.png)
> ![image](https://user-images.githubusercontent.com/1469350/73364819-1fde8280-42a3-11ea-9805-28ac58b65180.png)

which picture is grub2?

**Comment by steve6375** [comment]
Left side is grub4dos good grub4dos, right side is bad (grub2)

**Comment by a1ive** [comment]
grub2/windows will ignore chs in mbr, so the partition can be read by grub2/windows.

**Comment by a1ive** [comment]
The code to calculate chs is from coreos and grub-legacy, I don't know bios things and how to calculate it correctly.

**Comment by steve6375** [comment]
its odd, the grub4dos CHS seems wrong to me - yet it works and the grub2 ones do not???

**Comment by steve6375** [comment]
I think the CHS should be  FE FF FF.
If I change it to this, then it works OK.
Also the LBA size seems out by 1 - partnew command says LENGTH=74219  and then says LENGTH=74218 - so out by 1 somewhere?

Not sure what the grub4dos CHS parameters are about or why they work! Seems like a bug in grub4dos which seems to work anyway ?

**Comment by a1ive** [comment]
https://github.com/a1ive/grub/blob/b3fefa3ac4c5ac286ee4868c2925c96b663092df/grub-core/commands/partnew.c#L101

**Comment by steve6375** [comment]
OK
so CHS is currently  FF FF FF  and it should be FE FF FF

and size needs adjusting by 1

**Comment by steve6375** [comment]
File is 38,000,000 bytes = 74218.75 sectors
so size needs to be 74219 =121EB hex

**Comment by a1ive** [comment]
![截图录屏_选择区域_20200531154846](https://user-images.githubusercontent.com/10670106/83347253-7db8cf00-a356-11ea-997d-9d7cbb59a4f7.png)
???
The CHS in mbr in a GPT partmap should be FF FF FF?

**Comment by steve6375** [comment]
Is that for a GPT protective MBR partition entry only (|GPT disk)?
Presumably you use FFFFFFFF only if the disk is larger than 2TB-ish?
Maybe grub4dos has a problem seeing GPT disks over 2TB?
I don't have a drive > 2TB - I wonder what this field is set to by Windows/Linux?

**Comment by a1ive** [comment]
> Is that for a GPT protective MBR partition entry only (GPT disk)?

yes.
will grub4dos read chs from gpt protective mbr?

**Comment by steve6375** [comment]
grub4dos can read GPT disks (but not boot from them), so it should use the GPT partition parameters and ignore the protective MBR when accessing volumes\partitions.
I don't have a spare >128Gb drive I can convert to GPT at the moment to experiment.
