### ISSUE TITLE
Add first-character menu jump feature

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#31]
grub4dos it has a useful menu feature where you can press a key to jump to the menu entry that begins with that key.
e.g. If you press the P key, it will select the next menu entry that begins with the letter p or P. If you press the P key again, it will select the next menu entry down (or the first menu entry beginning with P or p if there is no menu entry beginning with P below it).
Menu hotkeys such as e, c, etc.  must be invoked using the shift key (e.g. SHIFT+c for command prompt, SHIFT+e for edit).
Key names should be used (not key scan codes) for differently labelled keyboards (e.g. QWERTZ, AZERTY).
This may be too difficult to implement but it would be a useful feature when we have large/long menus.

**Comment by a1ive** [comment]
How to jump to menu entries begin with non-ascii characters(Chinese characters)?
This feature may be in conflict with `menuentry --hotkey` options.

**Comment by steve6375** [comment]
True. I was thinking mainly for agFM.
What if agFM defined a hotkey using the first letter of the name of the file for each filename entry?

**Comment by a1ive** [comment]
> Does the menuentry hotkey just select the entry or does it execute it as well?

execute

**Comment by rdragonz** [comment]
Windows does a similar thing via holding the LALT key and then underlining a key letter on most clickable options. A similar thing could be implemented.

**Comment by a1ive** [comment]
@steve6375 please try it. 
[grubfmx64.efi.zip](https://github.com/a1ive/grub/files/5251637/grubfmx64.efi.zip)
test menu
[a.cfg.txt](https://github.com/a1ive/grub/files/5251639/a.cfg.txt)

only supports A-Z (a-z), case insensitive.

**Comment by a1ive** [comment]
[grubfmx64.efi.zip](https://github.com/a1ive/grub/files/5251867/grubfmx64.efi.zip)

**Comment by steve6375** [comment]
Seems to be an issue with using a \boot\grubfm\config file to define an initial boot menu.

menu jump works fine in the config menu, but when I execute grubfm - then the disable_edit and disable_console hotkeys still are disabled, but the menu jump feature is not working in the new grubfm menu.

config

```
export grub_disable_console=1
export grub_disable_edit=1
export grub_enable_menu_jump=1

	menuentry "a1ive grub2 File Manager" --class=dir {
		grubfm
	}

```

**Comment by steve6375** [comment]
Also ignore any starting character which is not a-zA-z. This means user can name files to make sure they appear in menu first but jump will still work:

!mefirst.iso        (m is used as jump letter)
_ubuntu_x64.iso  (u is used as jump letter)
archlinux.iso   
ubuntu.iso
_ ubuntu.iso   (_ and [space] are ignored for auto jump - u is used as jump letter)



P.P.S. A useful feature I added to E2B is to ignore any leading _*_ in a filename

for instance, the user can rename an ISO file as  `_001_Ubuntu.iso`
but it is displayed in the menu as
**Ubuntu.iso**

but it is sorted according to its characters _001_Ubuntu.iso so that it is listed first (or early) in the menu.
pressing u key (any case) will cause it to jump to the item starting with u.

This means it is very easy for the user to arrange the menu items in order, merely by using `_001_ _002_ _100_ `etc, at the beginning of each file.

_001_Ubuntu.iso
_002_Ubuntuv4.1.iso
_011_Ubuntuv5.2.iso
_800_Ubuntu2.6.iso

**Comment by a1ive** [comment]
> Seems to be an issue with using a \boot\grubfm\config file to define an initial boot menu.
> 
> menu jump works fine in the config menu, but when I execute grubfm - then the disable_edit and disable_console hotkeys still are disabled, but the menu jump feature is not working in the new grubfm menu.
> 
> config
> 
> ```
> export grub_disable_console=1
> export grub_disable_edit=1
> export grub_enable_menu_jump=1
> 
> 	menuentry "a1ive grub2 File Manager" --class=dir {
> 		grubfm
> 	}
> ```

menu jump only works in normal config menu. grubfm uses another menu system.

**Comment by steve6375** [comment]
:-(  would be very useful in grubfm!

**Comment by a1ive** [comment]
> :-( would be very useful in grubfm!

conflict with "[F] search".

**Comment by steve6375** [comment]
[F] search doesn't work well anyway - can't exit out of it and dependant on theme.
I prefer not to have F search function

**Comment by steve6375** [comment]
or change to use F9 ?

**Comment by a1ive** [comment]
No. I like 'c' and 'e' hotkeys. I will not ban them by default in grubfm.

**Comment by steve6375** [comment]
I don't want to ban e and c by default! I did not suggest this!
I was suggesting that you change the F hotkey in grubfm to F9 (or some other Fx key).
This would mean the end user could use the **config** **file** to  disable e and c and enable jump feature in grubfm.

**Comment by a1ive** [comment]
now you can also use this feature in grubfm.
I'm considering to change the hotkey of '[F] Search' to another key, e.g. Ctrl+Shift+F.

**Comment by steve6375** [comment]
OK
F Search function has bugs anyway!
If you press F  then you cannot go back

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/94142394-1d4e2000-fe66-11ea-8e55-1bc7a25c7237.png)
![image](https://user-images.githubusercontent.com/1469350/94142407-26d78800-fe66-11ea-9b41-73ca4fa03bdf.png)
![image](https://user-images.githubusercontent.com/1469350/94142515-5090af00-fe66-11ea-976d-063ad3e55236.png)
STUCK !!! MUST CHOOSE A FILE.

**Comment by steve6375** [comment]
A setting to change c and e  to  ctrl+shift+c and ctrl+shift+e  would also be nice.
Then the user would still have those two functions which could be used with auto_jump feature.
