### ISSUE TITLE
Optimize blocklist speed

### ISSUE THREAD

**Issue by a1ive** [a1ive/grub#33]
https://github.com/a1ive/grub2-filemanager/issues/95

https://github.com/chenall/grub4dos/commit/756d924cb61f861773ab793181f777ab4495ae8e
https://github.com/chenall/grub4dos/commit/bcc4b7b932f28129f0578c724f8a1aac35e71b13

**Comment by a1ive** [comment]
now should work on FAT and exFAT.

**Comment by steve6375** [comment]
Thanks - will test. Does partnew command now use this and report error if the specified file is non-contiguous?

**Comment by a1ive** [comment]
> Does partnew command now use this and report error if the specified file is non-contiguous?

No.I don't think partnew should forbid it.

**Comment by steve6375** [comment]
But a partition MUST be contiguous.
grub4dos partnew tests for it and refuses to use the file if it is not contiguous.

**Comment by a1ive** [comment]
@steve6375 Does GRUB4DOS partnew and fast blocklist work on Compressed NTFS?

**Comment by steve6375** [comment]
I don't think grub4dos supports compressed NTFS (I have never tested it though).

**Comment by steve6375** [comment]
This is what happens if partnew uses a non-contiguous 3GB file.
The partition assumes contiguous 3GB of space on disk!
if the user formatted the new partition (e.g. to install an OS, etc.) then it would corrupt the drive.

![image](https://user-images.githubusercontent.com/1469350/75326428-83dc7280-5872-11ea-846e-42b0946122e2.png)
Partition 4   SIZE=2929.469MiB   Type: 07 NTFS\exFAT       
START POS   = CYL:1023 HD:254 SEC:63       END POS = CYL:1023 HD:254 SEC:63
START (LBA) = 110,210,856 (0691AF28) SIZE (LBA) = 5,999,552 (005B8BC0) [End=116,210,407]

**Comment by steve6375** [comment]
Does not seem any quicker? Is it in release download yet?
![image](https://user-images.githubusercontent.com/1469350/75334342-90b39300-587f-11ea-980c-ad4e7520cbb0.png)

**Comment by a1ive** [comment]
file in fat/exfat partition?

**Comment by steve6375** [comment]
NTFS

**Comment by steve6375** [comment]
FAT32 seems quick
![image](https://user-images.githubusercontent.com/1469350/75335216-fbb19980-5880-11ea-8c96-9962e6af6cf0.png)

**Comment by a1ive** [comment]
Now it works on NTFS and ext*.
But doesn't work on compressed NTFS.

**Comment by steve6375** [comment]
Thanks, I will test. Does partnew automatically fail if the specified file is not contiguous?

**Comment by a1ive** [comment]
> Thanks, I will test. Does partnew automatically fail if the specified file is not contiguous?

No.You should check it manually before `partnew`.
contig/blocklist check don't work on some filesystems.

**Comment by steve6375** [comment]
Also, in grubfm, any menu entry which uses partnew\easy2boot option should not list that menu entry is the file is nn-contiguous.

**Comment by steve6375** [comment]
and show contiguous state in File Info (info.sh)?

**Comment by steve6375** [comment]
For those filesystems that are supported, I strongly recommend that partnew does check for non-contiguous and will fail if the file is contiguous.

1. Use uses partnew on a non-contiguous ISO  - result - ISO fails to boot but user has no idea why

1. Use partnew on a blank.imgPTN file which is non-contiguous
2. User formats the new blank partition - result many files on the USB drive are destroyed and drive is corrupted.
