### ISSUE TITLE
partnew does not clear CHS values

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#34]
Using partnew type 0 start 0 length 0 does not change the CHS values to 0

![image](https://user-images.githubusercontent.com/1469350/74641125-b0a0d380-5168-11ea-9fc1-2b6fa150cd2d.png)

**Comment by steve6375** [comment]
P.S. partnew has no -q  (quiet switch)

**Comment by a1ive** [comment]
> P.S. partnew has no -q (quiet) switch

I don't think it's useful.

**Comment by steve6375** [comment]
I want to clear type 0 partitions of all parameters silently

easy2boot\partnew will set a type 0 partition in ptn4 - you then can boot to say Manjaro.
Now you reboot and choose a loopback boot of say Ubuntu
but Ptn4 still has Manjaro  as type 0 which will be detected by Ubuntu on boot. The user will see a Manjaro partition on the USB drive.

In Easy2Boot, I clear ptn4 on each boot to the menu, .i.e.

if ptn4 type=0 then clear ptn 4

I dont really want this on the screen.

**Comment by steve6375** [comment]
I was going to add something like this to the config file...
```
 # if type 0 in any of the 4 partition tables in MBR then clear the table entry
set x=NONE
hexdump -q -s 0x1c2 -n 1 (hd0)0+1 x
if [ "$x" = "\x00" ] ; then partnew -t 0 -s 0 -l 0 "${grubfm_disk}" 1; fi
set x=NONE
hexdump -q -s 0x1d2 -n 1 (hd0)0+1 x
if [ "$x" = "\x00" ] ; then partnew -t 0 -s 0 -l 0 "${grubfm_disk}" 2; fi
set x=NONE
hexdump -q -s 0x1e2 -n 1 (hd0)0+1 x
if [ "$x" = "\x00" ] ; then partnew -t 0 -s 0 -l 0 "${grubfm_disk}" 3; fi
set x=NONE
hexdump -q -s 0x1f2 -n 1 (hd0)0+1 x
if [ "$x" = "\x00" ] ; then partnew -t 0 -s 0 -l 0 "${grubfm_disk}" 4; fi
unset x
```

to see if it worked OK or caused any issue...

**Comment by steve6375** [comment]
Thanks!
