### ISSUE TITLE
cp help

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#38]
Does not specify which is source and which is destination?
![image](https://user-images.githubusercontent.com/1469350/75099873-a0e91b00-55be-11ea-8db3-5f68f111d613.png)
Is this for FAT filesystems only? What if source file is larger than the destination file?
![image](https://user-images.githubusercontent.com/1469350/75099970-c9bde000-55bf-11ea-8e20-b5714b3ccfe9.png)

**Comment by a1ive** [comment]
see http://bbs.wuyou.net/forum.php?mod=viewthread&tid=418985

**Comment by a1ive** [comment]
Destination should be FAT (all platform) or exFAT(x86_64-efi/arm64-efi).

**Comment by a1ive** [comment]
You need to mount a fat partition first.
e.g.
```
mount (hd0,1) 1
cp (hd0,2)/xxx/yyy.img 1:/zzz/www.img
cp 1:/abc/def.zip 1:/qwe/rty.zip
```
If dest_file not exist, it will be created.
If dest_file exists, it will be truncated and overwritten.
> What if source file is larger than the destination file?

It's just like normal os (win `copy` and linux `cp`).
