### ISSUE TITLE
Enhancement: Display value of grubfm_current_path at top of menu

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#40]
e.g. Which drive\folder am I looking at?
![image](https://user-images.githubusercontent.com/1469350/75144393-bcebda00-56ee-11ea-96d0-8b6526a9179d.png)

**Comment by a1ive** [comment]
It's difficult to implement.

**Comment by steve6375** [comment]
Maybe change the first entry
..
so it shows  
..  (@ (hd0,msdos1)/_ISO/MAINMENU/)

?

**Comment by a1ive** [comment]
This could be confusing. I think ".." means parent folder.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/75151469-abaac980-56fe-11ea-8e0b-dcc6ae0293e4.png)

**Comment by steve6375** [comment]
@ means at this current level?

or maybe...
![image](https://user-images.githubusercontent.com/1469350/75151596-fd535400-56fe-11ea-89df-f4819714850d.png)

**Comment by steve6375** [comment]
I think this is OK
![image](https://user-images.githubusercontent.com/1469350/75151874-95e9d400-56ff-11ea-93d9-2f9375749462.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/75151933-c6ca0900-56ff-11ea-8c8e-23373b9547a1.png)
??

**Comment by a1ive** [comment]
> I think this is OK
> ![image](https://user-images.githubusercontent.com/1469350/75151874-95e9d400-56ff-11ea-93d9-2f9375749462.png)

This looks good.

**Comment by steve6375** [comment]
OK - is it easy to do?

**Comment by a1ive** [comment]
> OK - is it easy to do?

yes
