### ISSUE TITLE
Enhancement: clear all loopback drives if top level reached in grubfm

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#41]
if you select an ISO, etc, but don't run it, then go back to the top level
you see mounted loopbacks, etc. which is confusing

(or is this a feature?)

![image](https://user-images.githubusercontent.com/1469350/75153619-bfa4fa00-5703-11ea-9849-6a9ab1af59a7.png)

**Comment by steve6375** [comment]
Maybe add into an F4 or F6 menu

mount file as loopback and explore contents?

**Comment by steve6375** [comment]
Maybe option in the 'Open' menu

Explore file contents

![image](https://user-images.githubusercontent.com/1469350/75155202-6b9c1480-5707-11ea-8276-e35e0b1804c2.png)

**Comment by steve6375** [comment]
I just recompiled and selected a Kaspersky Rescue Disk ISO and then went back to top level
UEFI64
![image](https://user-images.githubusercontent.com/1469350/75238787-79aa6d80-57b9-11ea-9a40-0a3cbb4b8dff.png)

**Comment by a1ive** [comment]
???
can't reproduce.
![深度录屏_选择区域_20200225190342](https://user-images.githubusercontent.com/10670106/75241737-a3878280-5801-11ea-8f4a-4614cdc3c8da.gif)

**Comment by steve6375** [comment]
Sorry - my fault - I did not update my user files!
