### ISSUE TITLE
dd (proc) or blocksize issue?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#42]
when using dd -if=(proc) to fill a 100K file with 00's, it takes about 70 seconds.
However, if I add bs=512 it is much quicker.
What are valid values for --bs?
I tried numbers larger than 512 but they are not accepted?
P.S. help dd does not mention (proc) usage or give valid values for --bs.

**Comment by a1ive** [comment]
Now support bs from 1 to 4096.
> P.S. help dd does not mention (proc) usage

I don't think we should introduce usage of (proc) in `dd`.You could also use it in `hexdump`.

**Comment by steve6375** [comment]
Thanks.
I now need to fill an xml file with spaces before overwriting it with the contents of a smaller file.
This is because Windows Setup stops with an invalid XML message if the XML file contains 00 bytes.
How can I fill a file with spaces?

**Comment by a1ive** [comment]
You could prepare an XML file filled with spaces, and compress it to cpio/tar.gz.
Then run `loopback -m xml xxx.cpio` to load it to memory.
You could write strings to it without modifying the real file on disk.

**Comment by steve6375** [comment]
that works. thanks.
