### ISSUE TITLE
Speed up blocklist and stat -c

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#43]
Is it possible to speed these up? They really are unusable at the moment.
doing a stat -c on a large 3GB ISO takes minutes.
Is this a blocksize problem (like using --bs=512 works for dd?)

**Comment by a1ive** [comment]
I tried to modify some codes, which can successfully speed up blocklist file in FAT partition.
However it crashes on NTFS.

**Comment by steve6375** [comment]
Please don't give up. It really is important because any file which is used by partnew must be contiguous and so we should always check that the file is contiguous before using it...

**Comment by a1ive** [comment]
This issue is duplicated (#33), plz close.
