### ISSUE TITLE
document: insensitive case tests not documented?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#45]
![image](https://user-images.githubusercontent.com/1469350/75342614-aaa8a200-588e-11ea-845d-7bffdd2392bb.png)

https://a1ive.github.io/grub2_cmd_zh.html

**Comment by steve6375** [comment]
Better to use -D and -E and -F in scripts when looking for files\dirs inside ISOs etc. and in user folders which could be on NTFS or exFAT volumes?

**Comment by a1ive** [comment]
Are you sure?
![深度截图_选择区域_20200226201144](https://user-images.githubusercontent.com/10670106/75343835-44df0900-58d4-11ea-9ba5-c83975ec460c.png)

**Comment by steve6375** [comment]
oh! no sorry! I thought I had discovered some useful feature!
Would it be useful to support -F, -D and -E  for case-insensitive test?
(it was what I was about to ask for when I tested it to see if it already existed).

**Comment by steve6375** [comment]
Better yet, some function to get the filename of a file regardless of it's case, e.g.

`getpath -s truename (hd0,msdos1)/Qwert/aAa.txt
`

returns $truename as (hd0,msdos1)/qwert/aaa.txt

getpath -s truename `/Qwert/aAa.txt`

returns $truename as /qwert/aaa.txt

**Comment by a1ive** [comment]
![深度截图_选择区域_20200226204202](https://user-images.githubusercontent.com/10670106/75346352-7d351600-58d9-11ea-88c4-1e35857c44c5.png)
[grubfmx64.efi.zip](https://github.com/a1ive/grub/files/4255751/grubfmx64.efi.zip)
It seems that I've managed to make ntfs case-insensitive.
I'm not sure, please try it.

**Comment by a1ive** [comment]
Please test it on different filesystems (e.g. NTFS/iso9660/udf/ext4 ...)
set `grub_fs_case_sensitive` to 1 to enable case-sensitive, other value or unset to make it case-insenstive.
Some filesystem will ignore this variable (e.g. FAT/exFAT/newc ...)?

**Comment by steve6375** [comment]
Looks good so far. Great work!
