### ISSUE TITLE
enhancement: set command can use partial match

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#47]
grub4dos has a very useful feature.
if you type on command line
set gr
it will list all variables beginning with 'gr'
Could this be implemented for grub2 please?

**Comment by a1ive** [comment]
It's possible, but I don't think it's important.
I will try to implement it if I have time.

completion
https://github.com/a1ive/grub/blob/d68f63f7531e4e05a8c88d726107c9bea939b08a/grub-core/normal/completion.c#L322-L332
list variable
https://github.com/a1ive/grub/blob/d68f63f7531e4e05a8c88d726107c9bea939b08a/grub-core/kern/corecmd.c#L41-L44

**Comment by a1ive** [comment]
![深度截图_选择区域_20200301152017](https://user-images.githubusercontent.com/10670106/75621723-03e83c80-5bd3-11ea-9e1d-d94e9ffce2e4.png)

**Comment by steve6375** [comment]
Doesn't seem to be in today's build?

**Comment by steve6375** [comment]
Oh sorry - it uses TAB for auto completion. OK, I see. Not the same as grub4dos but just as good :-) Thanks!
