### ISSUE TITLE
read command does not understand <backspace> or <del> keys

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#49]
`read a`
type
`fred[BS][BS]doris`
`echo $a`

result:
freddoris

also cursor keys add a letter - e.g. 'K' = left or 'M' = right
DEL key adds 'S'

**Comment by steve6375** [comment]
P.S. would also be nice to have a  read -q switch (does not echo characters on screen) and a read -p switch (prints * instead of the typed character) for password entry.

**Comment by a1ive** [comment]
These features can be implemented using Lua scripts.

**Comment by steve6375** [comment]
I tried that but couldn't see how to call it?
https://inspired-lua.org/index.php/tag/backspace/
Could you give me a clue?

**Comment by a1ive** [comment]
now you can use 'backspace' in read command.
> also cursor keys add a letter - e.g. 'K' = left or 'M' = right

bug fixed.
> could also be nice to have a read -q switch (does not echo characters on screen)

use `read VAR h` (hide)
> read -p switch (prints * instead of the typed character) for password entry.
use `read VAR a` (asterisk)

**Comment by steve6375** [comment]
Thanks. Very nice! BS works
but left-cursor and right-cursor is still adding K and M
DEL is adding 'S'
![image](https://user-images.githubusercontent.com/1469350/75677160-bb885780-5c82-11ea-91a1-b82a20ca06c6.png)

**Comment by steve6375** [comment]
That's got it 👍
