### ISSUE TITLE
hexdump not working from UEFI on some PCs/notebooks

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#51]
Dell Vostro 3558
MacBook

Some users report a problem with switching in .imgPTN files.
On a MacBook, hexdump does not work and returns all 00's
![image](https://user-images.githubusercontent.com/1469350/76234891-3a9d0300-6222-11ea-9ba8-21c71bc52763.png)

Works OK on my IdeaPad 300 and Asus Z87 PC.

Same users reports no problem using MBR\Legacy booting using same code for .imgPTN.

Any ideas? Maybe dd also does not work in UEFI on these models (untested)?

**Comment by a1ive** [comment]
I have no idea.

**Comment by a1ive** [comment]
SecureBoot on/off?

**Comment by steve6375** [comment]
User says thinks it is with Secure Boot off. I have 3 people now reporting same issue on some models of PC\notebook.

**Comment by steve6375** [comment]
Closing this issue - it could be because UEFI is not booting USB boot drive as drive 0.
Some UEFI BIOSes boot it as hd1 or hd2 or hd3!
