### ISSUE TITLE
parttool cannot set partition type of a type 0 MBR partition

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#54]
![image](https://user-images.githubusercontent.com/1469350/79446848-d581bd80-7fd6-11ea-9e56-21b9cff8dc09.png)

**Comment by a1ive** [comment]
Yes. because hd0,2 is not a valid partition if type is 0x00.
I'm thinking about how to solve it.
Do you have any idea?
maybe we could let grub2 'recognize' type 0x00 partition?

**Comment by steve6375** [comment]
maybe we could let grub2 'recognize' type 0x00 partition?
I think that would be a bad idea. It may break compatability.

if partition is valid MBR (ends 55 AA) maybe use --force command

parttool (hd0,2) type=0xEF --force

Then is uses dd to write byte?

**Comment by a1ive** [comment]
`parttool` module is very complex, needs to be rewritten.
`dd` is a simple workaround.

**Comment by steve6375** [comment]
Cant you just test for --force and run separate code to just change the one byte?
If not, I will have to use dd.

**Comment by a1ive** [comment]
[grubfmx64.efi.tar.gz](https://github.com/a1ive/grub/files/4486689/grubfmx64.efi.tar.gz)

I modified `partnew` command.
usage:
partnew --type=0x00 hd0 4
(no `--start` `--length` `--file` options)
USE WITH CAUTION!

**Comment by steve6375** [comment]
so I can use type=0x00 to set default type
or --type=0xEF to set specific type and it will not change  other values in the partition table?

**Comment by a1ive** [comment]
yes. only change part type (and active flag if with `--active`).

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/79451421-72942480-7fde-11ea-864d-799a23ebe3d0.png)
Not detecting type ??

**Comment by a1ive** [comment]
> so I can use type=0x00 to set default type

sorry, no auto-detection for 0x00 or 0x10

**Comment by steve6375** [comment]
So auto-detect for type 0 only works when file or start length params used?

**Comment by a1ive** [comment]
yes.

**Comment by steve6375** [comment]
OK - seems to work. 👍 
Can help for partnew be updated?
![image](https://user-images.githubusercontent.com/1469350/79452414-09adac00-7fe0-11ea-9657-3be9afd9d3c1.png)
