### ISSUE TITLE
Query: How to get RAM size of system

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#55]
In grub4dos I can get the total amount of RAM in a system.
How can I do this with grub2 (MBR and UEFI)?
For instance, I can automatically select a 32-bit install of Windows from a dual architecture ISO if the system has <4GB of RAM. Or run a 32-bit version of Linux if <4GB of RAM instead of the 64-bit version.

**Comment by a1ive** [comment]
Legacy-BIOS?
I have no idea.

**Comment by steve6375** [comment]
UEFI BIOS?

**Comment by a1ive** [comment]
>  I can automatically select a 32-bit install of Windows from a dual architecture ISO if the system has <4GB of RAM.

You can't boot/install a 32-bit Windows if UEFI firmware is 64-bit.

**Comment by steve6375** [comment]
Sure , in that case I was thinking of Legacy boot.
But you can run Linux 32-bit kernels from UEFI64 boot (for instance).

**Comment by a1ive** [comment]
> But you can run Linux 32-bit kernels from UEFI64 boot (for instance).

compatibility of 32-bit linux is bad. It doesn't work no some tablets with 64-bit CPU/UEFI.
besides many linux distros (eg. Ubuntu) have dropped support for 32-bit.

**Comment by a1ive** [comment]
> Sure , in that case I was thinking of Legacy boot.

How to get the total amount of RAM in grub4dos?

**Comment by steve6375** [comment]
```
set /a M=*0x8298 & 0xffffffff>>10+1 > nul && set /a M1=*0x82c0>>10+1 > nul
set /a M=%M% + %M1% > nul
```
grub4dos has documented memory location where it is stored.
0000:8298       4 (DWORD) saved_mem_upper (extended memory size in KB)
0000:829C       4 (DWORD) saved_partition (current root partition) Only 2nd WORD is valid - use set /A PART=*0x829e&0xff (or set /a cur_pri=*0x829C>>16&0xFFFF)
0000:82A0       4 (DWORD) saved_drive (current root drive) set /a cur_drv=*0x82A0&0x7F
0000:82A4       4 (DWORD) no_decompression (no auto gunzip)  1=no decomp
0000:82A8       8 (QWORD) part_start (start sector of last partition)
0000:82B0       8 (QWORD) part_length (total sectors of last partition)
0000:82C0       8 (QWORD)       saved_mem_higher (max contiguous mem in KB starting at 4G

can do a BIOS call, int15 e820h
https://wiki.osdev.org/Detecting_Memory_(x86)#BIOS_Function:_INT_0x15.2C_EAX_.3D_0xE820

See grub4dos stage2\common.c for code.

**Comment by a1ive** [comment]
It seems that we can't get correct RAM size in vbox UEFI firmware?
![深度截图_选择区域_20200417165255](https://user-images.githubusercontent.com/10670106/79551600-74d4ac80-80cc-11ea-89c8-ef38d4707fa6.png)
```
 insmod /xxx/lsefimmap.mod
lsefimmap
```
in vm settings, RAM = 8192 MB, but in uefi, RAM = 4GB + 4608 MB ???

**Comment by steve6375** [comment]
That is showing memory above 4GB
You need to add up all conv-mem entries to get total memory?

**Comment by a1ive** [comment]
use `stat -r` to get ram size (MiB).
uefi is correct, but bios is not.
![深度截图_选择区域_20200417192008](https://user-images.githubusercontent.com/10670106/79564041-81630000-80e0-11ea-83f2-4fa6ea26c16d.png)
![深度截图_选择区域_20200417191929](https://user-images.githubusercontent.com/10670106/79564057-8758e100-80e0-11ea-8653-98c765a02a57.png)

**Comment by steve6375** [comment]
What variable is the result returned in?

**Comment by a1ive** [comment]
download latest build.
stat -q -r -s a
echo $a
![深度截图_选择区域_20200417201506](https://user-images.githubusercontent.com/10670106/79568336-3e0c8f80-80e8-11ea-9bac-2c17149f60c7.png)

**Comment by steve6375** [comment]
Thanks. MBR result agrees with grub4dos within +/-1. 👍

**Comment by steve6375** [comment]
Thanks - great work!
