### ISSUE TITLE
Add non-US keyboard support to read command

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#57]
The main (only?) way to get keyboard input when in the grub2 menu system is via the **read** command.
The terminal_input at_keyboard + keymap commands causes severe reliability issues with grub2, and it cannot be used.
Dealing with French (AZERTY) and German (QWERTZ) and other keyboards is still not working in grub2. This is a big problem!

Would it be possible to add simple keyboard support to the read command (or perhaps to whatever 'getkey' call is used by the read command) to 'translate' the keyboard characters. This may not solve the problem for entering commands at the terminal, but it would solve the problem of user input using the read command (e.g. name, password, etc.).

e.g. Add a new command to change a keyboard character on input so the **read** command returns the correct character.

setkey <new character> <old US kbd character>

Here is an example for grub4dos which uses a batch file for a german qwertz keyboard:
```
!BAT
#GERMAN
errorcheck off
#clear all settings
setkey
#setkey [new character] [QWERTY-USA character]
setkey z y
setkey Z Y
setkey y z
setkey Y Z
setkey doublequote at
setkey ampersand caret
setkey slash ampersand
setkey parenleft asterisk
setkey parenright parenleft
setkey equal parenright
setkey question underscore
setkey backslash minus
setkey plus bracketright
setkey asterisk braceright
setkey semicolon less
setkey colon greater
setkey minus slash
setkey backslash Aminus
setkey underscore question
setkey caret backquote
setkey quote equal
setkey backquote plus
setkey bracketleft semicolon
setkey braceleft colon
setkey bracketright quote
setkey braceright doublequote
setkey bar bracketleft
setkey at braceleft
setkey numbersign backslash
setkey at Aq
setkey less oem102
setkey greater shiftoem102
setkey braceleft A7
setkey bracketleft A8
setkey bracketright A9
setkey braceright A0
setkey tilde Abracketright
setkey backslash Aminus

#key names
#escape, exclam (!), at (@), numbersign (#), dollar ($), parenright ()), caret (^), ampersand (&), asterisk (*), plus (+), percent (%)
#minus (-), underscore (_), equal (=), parenleft [(], backspace (backspace), tab (Tab), bracketleft ([), braceleft ({), bracketright (])
#braceright (}), enter (carriage return), semicolon (;), colon (:), quote (') , doublequote ("), slash (/), backquote (`), tilde (~)
#backslash (\), bar (|), comma (,), less (<) period (.) , greater (>), question (?)
#space, home, uparrow, pageup, leftarrow, center, rightarrow, end, downarrow, pagedown, insert, delete, F1-F10, shiftF1-shiftF10, ctrlF1-ctrlF10
#Use prefix A for Alt+, e.g. Aequals, Aq, Aslash, A0, etc. Also oem102 and shiftoem102.
```

**Comment by a1ive** [comment]
I've already planned to add this feature ( I'm thinking about volume key support for tablet users.)
but I can't promise you that it will be better than `at_keyboard`

**Comment by steve6375** [comment]
OK, using the same key words as used by setkey for grub4dos would save a lot of work in making the translation files ;-)

**Comment by a1ive** [comment]
Actually, I prefer hexadecimal digits, eg. `setkey 0x7a 0x79`.

**Comment by steve6375** [comment]
That is not user friendly. It makes it very tricky to make translations files for all the keyboards and very difficult to find errors, etc.
grub4dos uses a table to translate the key names to hex characters, which is MUCH more user friendly and will save many hours of frustrating work having to make hex key files. Also some keyboard scan codes are multiple bytes. See grub4dos code stage2\builtins.c.

**Comment by a1ive** [comment]
scan codes of volume keys may not be a valid ASCII character, so I will try to add support for hex first.

**Comment by a1ive** [comment]
(in grub4dos/stage2/builtins.c)
![深度截图_选择区域_20200422095350](https://user-images.githubusercontent.com/10670106/79932097-487bb000-847f-11ea-9c57-b8d63cfdf014.png)
why no F11 and F12 in grub4dos?

**Comment by a1ive** [comment]
```
/* The table for key symbols. (from GRUB4DOS) */
static struct keysym keysym_table[] =
{
  {"escape",        GRUB_TERM_ESC},    // ESC
  {"exclam",        0x21},    //    '!'
  {"at",            0x40},    //    '@'
  {"numbersign",    0x23},    //    '#'
  {"dollar",        0x24},    //    '$'
  {"percent",       0x25},    //    '%'
  {"caret",         0x5E},    //    '^'
  {"ampersand",     0x26},    //    '&'
  {"asterisk",      0x2A},    //    '*'
  {"parenleft",     0x28},    //    '('
  {"parenright",    0x29},    //    ')'
  {"minus",         0x2D},    // -
  {"underscore",    0x5F},    //    '_'
  {"equal",         0x3D},    // =
  {"plus",          0x2B},    //    '+'
  {"backspace",     GRUB_TERM_BACKSPACE},    // BS
  {"ctrlbackspace", 0x7F},    //     (DEL) //FIXME
  {"tab",           GRUB_TERM_TAB},    // Tab
  {"bracketleft",   0x5B},    // '['
  {"braceleft",     0x7B},    //    '{'
  {"bracketright",  0x5D},    // ']'
  {"braceright",    0x7D},    //    '}'
  {"enter",         0x0D},    // Enter
  {"semicolon",     0x3B},    // ';'
  {"colon",         0x3A},    //    ':'
  {"quote",         0x27},    // '\''
  {"doublequote",   0x22},    //    '"'
  {"backquote",     0x60},    // '`'
  {"tilde",         0x7E},    //    '~'
  {"backslash",     0x5C},    // '\\'
  {"bar",           0x7C},    //    '|'
  {"comma",         0x2C},    // ','
  {"less",          0x3C},    //    '<'
  {"period",        0x2E},    // '.'
  {"greater",       0x3E},    //    '>'
  {"slash",         0x2F},    // '/'
  {"question",      0x3F},    //    '?'
  {"space",         0x20},    // Space
  {"F1",            GRUB_TERM_KEY_F1},
  {"F2",            GRUB_TERM_KEY_F2},
  {"F3",            GRUB_TERM_KEY_F3},
  {"F4",            GRUB_TERM_KEY_F4},
  {"F5",            GRUB_TERM_KEY_F5},
  {"F6",            GRUB_TERM_KEY_F6},
  {"F7",            GRUB_TERM_KEY_F7},
  {"F8",            GRUB_TERM_KEY_F8},
  {"F9",            GRUB_TERM_KEY_F9},
  {"F10",           GRUB_TERM_KEY_F10},
  {"F11",           GRUB_TERM_KEY_F11},
  {"F12",           GRUB_TERM_KEY_F12},
  {"home",          GRUB_TERM_KEY_HOME},
  {"uparrow",       GRUB_TERM_KEY_UP},
  {"pageup",        GRUB_TERM_KEY_NPAGE},    // PgUp
  {"leftarrow",     GRUB_TERM_KEY_LEFT},
  {"center",        GRUB_TERM_KEY_CENTER},    // keypad center key
  {"rightarrow",    GRUB_TERM_KEY_RIGHT},
  {"end",           GRUB_TERM_KEY_END},
  {"downarrow",     GRUB_TERM_KEY_DOWN},
  {"pagedown",      GRUB_TERM_KEY_PPAGE},    // PgDn
  {"insert",        GRUB_TERM_KEY_INSERT},    // Insert
  {"delete",        GRUB_TERM_KEY_DC},    // Delete
  {"shiftF1",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F1},
  {"shiftF2",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F2},
  {"shiftF3",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F3},
  {"shiftF4",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F4},
  {"shiftF5",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F5},
  {"shiftF6",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F6},
  {"shiftF7",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F7},
  {"shiftF8",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F8},
  {"shiftF9",       GRUB_TERM_SHIFT | GRUB_TERM_KEY_F9},
  {"shiftF10",      GRUB_TERM_SHIFT | GRUB_TERM_KEY_F10},
  {"shiftF11",      GRUB_TERM_SHIFT | GRUB_TERM_KEY_F11},
  {"shiftF12",      GRUB_TERM_SHIFT | GRUB_TERM_KEY_F12},
  {"ctrlF1",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F1},
  {"ctrlF2",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F2},
  {"ctrlF3",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F3},
  {"ctrlF4",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F4},
  {"ctrlF5",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F5},
  {"ctrlF6",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F6},
  {"ctrlF7",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F7},
  {"ctrlF8",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F8},
  {"ctrlF9",        GRUB_TERM_CTRL | GRUB_TERM_KEY_F9},
  {"ctrlF10",       GRUB_TERM_CTRL | GRUB_TERM_KEY_F10},
  {"ctrlF11",       GRUB_TERM_CTRL | GRUB_TERM_KEY_F11},
  {"ctrlF12",       GRUB_TERM_CTRL | GRUB_TERM_KEY_F12},
  // A=Alt or AltGr.    Provided by steve.
  {"Aq",            GRUB_TERM_ALT | 0x71},
  {"Aw",            GRUB_TERM_ALT | 0x77},
  {"Ae",            GRUB_TERM_ALT | 0x65},
  {"Ar",            GRUB_TERM_ALT | 0x72},
  {"At",            GRUB_TERM_ALT | 0x74},
  {"Ay",            GRUB_TERM_ALT | 0x79},
  {"Au",            GRUB_TERM_ALT | 0x75},
  {"Ai",            GRUB_TERM_ALT | 0x69},
  {"Ao",            GRUB_TERM_ALT | 0x6F},
  {"Ap",            GRUB_TERM_ALT | 0x70},
  {"Aa",            GRUB_TERM_ALT | 0x61},
  {"As",            GRUB_TERM_ALT | 0x73},
  {"Ad",            GRUB_TERM_ALT | 0x64},
  {"Af",            GRUB_TERM_ALT | 0x66},
  {"Ag",            GRUB_TERM_ALT | 0x67},
  {"Ah",            GRUB_TERM_ALT | 0x68},
  {"Aj",            GRUB_TERM_ALT | 0x6A},
  {"Ak",            GRUB_TERM_ALT | 0x6B},
  {"Al",            GRUB_TERM_ALT | 0x6C},
  {"Az",            GRUB_TERM_ALT | 0x7A},
  {"Ax",            GRUB_TERM_ALT | 0x78},
  {"Ac",            GRUB_TERM_ALT | 0x63},
  {"Av",            GRUB_TERM_ALT | 0x76},
  {"Ab",            GRUB_TERM_ALT | 0x62},
  {"An",            GRUB_TERM_ALT | 0x6E},
  {"Am",            GRUB_TERM_ALT | 0x6D},
  {"A1",            GRUB_TERM_ALT | 0x31},
  {"A2",            GRUB_TERM_ALT | 0x32},
  {"A3",            GRUB_TERM_ALT | 0x33},
  {"A4",            GRUB_TERM_ALT | 0x34},
  {"A5",            GRUB_TERM_ALT | 0x35},
  {"A6",            GRUB_TERM_ALT | 0x36},
  {"A7",            GRUB_TERM_ALT | 0x37},
  {"A8",            GRUB_TERM_ALT | 0x38},
  {"A9",            GRUB_TERM_ALT | 0x39},
  {"A0",            GRUB_TERM_ALT | 0x30},
  {"oem102",        0x565c}, // FIXME
  {"shiftoem102",   0x567c}, // FIXME
  {"Aminus",        GRUB_TERM_ALT | 0x2D},
  {"Aequal",        GRUB_TERM_ALT | 0x3D},
  {"Abracketleft",  GRUB_TERM_ALT | 0x5B},
  {"Abracketright", GRUB_TERM_ALT | 0x5D},
  {"Asemicolon",    GRUB_TERM_ALT | 0x3B},
  {"Aquote",        GRUB_TERM_ALT | 0x27},
  {"Abackquote",    GRUB_TERM_ALT | 0x60},
  {"Abackslash",    GRUB_TERM_ALT | 0x5C},
  {"Acomma",        GRUB_TERM_ALT | 0x2C},
  {"Aperiod",       GRUB_TERM_ALT | 0x2E},
  {"Aslash",        GRUB_TERM_ALT | 0x2F},
};
```

**Comment by a1ive** [comment]
```
{"oem102",        0x565c},
{"shiftoem102",   0x567c},
```
what does "oem12" mean? how to get its scan code?
```
{"backspace",		0x0E08},	// BS
{"ctrlbackspace",	0x0E7F},	// 	(DEL)
```
what does "ctrlbackspace" mean? ctrl+backspace?

**Comment by steve6375** [comment]
The F keys normally dont required remapping as they dont generate characters.
F11 and F12 have non-standard codes on some notebooks or don't exist on some keyboards. I guess they were just omitted in grub4dos as the hotkey utility does not work with them.
F11 gives 8500 code,  F12 gives 8600 code on my UK keyboard.

ctrlsbackspace = ctrl+backspace
oem102 is the key on the left above the windows key - on UK 102-key keyboard it has \ and | characters.

The best reference for keyboards is http://kbdlayout.info/

**Comment by a1ive** [comment]
scan codes in grub2 / grub4dos are different.
my keyboard doesn't have the "oem102" key (no key between `shift` and `z`)
could you please execute `getkey` in grub2 and get the scan code of oem102?

**Comment by steve6375** [comment]
oem102 key = 0x5c
shift+oem102 key = 0x7c

**Comment by steve6375** [comment]
F11 = 0x00800085
F12 = 0x00800086

**Comment by a1ive** [comment]
please try.
![深度截图_选择区域_20200422150110](https://user-images.githubusercontent.com/10670106/79950843-411dcc00-84aa-11ea-9d4b-35149d1df84b.png)
[grubfmx64.efi.tar.gz](https://github.com/a1ive/grub/files/4514314/grubfmx64.efi.tar.gz)
e.g.
setkey 0x7a 0x79
setkey a b
setkey at Aq

use `setkey --enable` to enable remapping.

**Comment by a1ive** [comment]
fix bug.
[grubfmx64.efi.tar.gz](https://github.com/a1ive/grub/files/4514367/grubfmx64.efi.tar.gz)

**Comment by steve6375** [comment]
looks good so far
small bug in help
![image](https://user-images.githubusercontent.com/1469350/79952348-334c5480-8472-11ea-8f40-1115a71746bf.png)

**Comment by steve6375** [comment]
oem102 key is not working when using getkey (setkey not used) or after using setkey

boot
grub2 console
getkey
(press oem102 key)  >>> no response







Is it not supported at a lower level?

**Comment by steve6375** [comment]
[KBD.zip](https://github.com/a1ive/grub/files/4514956/KBD.zip)
Example scripts

**Comment by steve6375** [comment]
bug in table
Aequal  should be Aequals

**Comment by steve6375** [comment]
Found some bugs in the scripts. here is revised version.
[KBD_FILES.zip](https://github.com/a1ive/grub/files/4515513/KBD_FILES.zip)

**Comment by steve6375** [comment]
apart from oem102 key no longer working, it seems to be good - great work!

I guess an extra grubfm **F4** settings menu entry is required (because the keyboard used is not the same as the language picked)?
When the user picks a language in F4, you could set a default keyboard (e.g. if french language then pick KBD_FRENCH.cfg by default) or maybe ask if OK and if not present a list of keyboards to select from?

**Comment by a1ive** [comment]
> oem102 key is not working now when using getkey (setkey not used) 

this should not happen. 😕 
Is there any way to emulate this key in virtual machine?

**Comment by steve6375** [comment]
Here are results of REAL PC (I was using VBox 5 before):

UEFI64 boot
getkey (press oem102 key) -> 0x5c
getkey (press shift+oem102 key) -> 0x7c
run KBD_QWERTY_UK.sh
```
setkey -r
#setkey [new character] [QWERTY-USA character]
#change key map for UK keyboard
setkey at doublequote
setkey doublequote at
setkey tilde bar
setkey numbersign backslash
echo UK KBD MAP SET
setkey -e
```

> 
press oem102 key -> #
press shift+oem102 key -> ~
type
getkey (press oem102 key) -> 0x23
getkey (press shift+oem102 key) -> 0x7e
setkey --status
0x5c -> 0x23
0x7c -> 0x7e

**Comment by a1ive** [comment]
so `getkey` ok, but `read` not work?

**Comment by steve6375** [comment]
According to http://kbdlayout.info/00000452/scancodes
scancode for oem102 (OEM5) is 0x56 ??? VK = 0xDC

**Comment by steve6375** [comment]
So first problem is that on booting to new grubfmx64.efi, the oem102 key (OEM5) does not work in the grub2 console.

If I boot to old grub2 (before you added setkey) then oem102 key works (I get \ and | characters)

**Comment by a1ive** [comment]
please download latest release.
copy setkey.mod to usb drive.
boot to grub, test oem key.
then insmod /setkey.mod, test oem key

**Comment by steve6375** [comment]
you mean rebuild grubfm from release server?
Where is setkey.mod?

**Comment by a1ive** [comment]
oh, I see.
In grub2, backslash = 0x5c, same as oem102!
https://github.com/a1ive/grub/blob/897241287554f2402c357990dc68deb30202f2bb/grub-core/term/setkey.c#L80-L81
https://github.com/a1ive/grub/blob/897241287554f2402c357990dc68deb30202f2bb/grub-core/term/setkey.c#L173-L174

**Comment by steve6375** [comment]
yes, without setkey, oem5 key and oem7 keys both produce same characters (| and \)

**Comment by a1ive** [comment]
This problem can't be solved.

**Comment by steve6375** [comment]
grub2 is producing same key code for the OEM5 and OEM7 keys. Must be a table wrong in code somewhere?

**Comment by steve6375** [comment]
If cant be fixed, then would be best to remove oem102 and shiftoem102 from setkey.

**Comment by steve6375** [comment]
Do you have any plans to add this into grubFM menu system?

**Comment by a1ive** [comment]
Yes. I will add "Keyboard layout" to F4 menu, list all keyboards.

**Comment by steve6375** [comment]
Please can you add these to the table - they are missing (were not available in grub4dos) and needed for some keyboards e.g. Czech (because oem102 not available so we need to use extra alt codes)

{"Acolon",       GRUB_TERM_ALT | 0x3a},
{"Aplus",       GRUB_TERM_ALT | 0x2b},
{"Aless",       GRUB_TERM_ALT | 0x3c},
{"Aunderscore",       GRUB_TERM_ALT | 0x5f},
{"Agreater",       GRUB_TERM_ALT | 0x3e},
{"Aquestion",       GRUB_TERM_ALT | 0x3f},
{"Atilde",       GRUB_TERM_ALT | 0x7e},
{"Abraceleft",       GRUB_TERM_ALT | 0x7b},
{"Abar",       GRUB_TERM_ALT | 0x7c},
{"Abraceright",       GRUB_TERM_ALT | 0x7d},
{"Adoublequote",       GRUB_TERM_ALT | 0x22},

and double-check they are right!

I can then work on translation files for better function (because oem102 is missing it means some more work is required as characters like \ or | etc. need remapping).

**Comment by a1ive** [comment]
does latest build work well for these keys?

**Comment by steve6375** [comment]
New build is working, but I need to work on the new map files, some characters are still missing.
Will send revised files in a few hours...

**Comment by steve6375** [comment]
[setkey_maps.zip](https://github.com/a1ive/grub/files/4528980/setkey_maps.zip)
Here are the new tested maps files
The QWERTZ and AZERTY files are generic and not for any specific keyboard - you can omit them if you wish.
Where I have mapped non-standard keys to replace the missing oem102 keys, I display a message for a few seconds to inform the user. If you prefer you can remove the echo and sleep lines.

**Comment by steve6375** [comment]
great!
