### ISSUE TITLE
How to rename  FAT32 folder?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#58]
Trying to rename \EFI folder. What am I doing wrong?

![image](https://user-images.githubusercontent.com/1469350/80274402-f383a800-86d1-11ea-894e-f5b7f8637557.png)

**Comment by a1ive** [comment]
![深度截图_选择区域_20200425155646](https://user-images.githubusercontent.com/10670106/80274497-6b22f880-870d-11ea-9dbf-7843d90378cd.png)

**Comment by steve6375** [comment]
Sorry, it was a VBox issue!
