### ISSUE TITLE
query: use of (hd0,1) and (hd0,msdos1)/(hd0,gpt1)

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#59]
What is the difference between using (hd0,1)  or using (hd0,msdos1) or (hd0,gpt1)?
Can I always use hd0,1  wherever   (hd0,msdos1) or (hd0,gpt1) can be used so that it does not matter what the filesystem is?

**Comment by a1ive** [comment]
> Can I always use hd0,1

yes.

**Comment by steve6375** [comment]
thank
