### ISSUE TITLE
   Request for injecting custom 'winpeshl_ventoy.ini' and 'start_ventoy.bat' to within from agFM Partition to X:/Windows/System32 folder.

### ISSUE THREAD

**Issue by devdevadev** [a1ive/grub#62]
Hi..a1ive

Currently we use 'grubfm_startbat' variable to inject custom 'start_agfm.bat' to X:/Windows/System32 folder for some extra work within WinPE environment.

If possible do something similiar to 'grubfm_startbat' in Ventoy Boot Option so that we will be able to inject custom 'start_agfm.bat' within from USB Partition to X:/Windows/System32 folder.

You can inject the 'winpeshl_ventoy.ini' and 'start_ventoy.bat' at the same time when 32-bit or 64-bit version of vtoyjump.exe is injected as X:/Windows\System32\winpeshl.exe ?

Can we not use the same 'grubfm_startbat' variable within 'Ventoy Boot Option' ?

Thanks & Regards...

**Comment by a1ive** [comment]
Why not just use "Boot Windows From ISO" option?
It has better compatibility than Ventoy.

**Comment by devdevadev** [comment]
Yes...I am currently using "Boot Windows From ISO" option for Windows Install ISO and works perfectly. I just asked if also added in 'Ventoy Boot Option' so that can also use Ventoy option in future when it will be added to E2B+agFM.

Do you think it will be possible to have similiar 'grubfm_startbat' variable in 'Ventoy Boot Option' ?
