### ISSUE TITLE
Extract bootmgr and bootmgfw.efi from wimfile if not specified

### ISSUE THREAD

**Issue by gilliginsisland** [a1ive/grub#71]
Upstream wimboot can automatically extract bootmgr in bios mode and bootmgfw.efi in efi mode from the wim file when they are not specified in the command.

https://github.com/ipxe/wimboot/blob/55cfe8a36090db5413afbb47b58b5c5bfeff8ea5/src/main.c#L344
https://github.com/ipxe/wimboot/blob/55cfe8a36090db5413afbb47b58b5c5bfeff8ea5/src/efifile.c#L204

Together with the built in BCD store that you added, this would allow booting a boot.wim file without needing any other supporting files.

**Comment by a1ive** [comment]
The wimboot module in BIOS is still unstable and compatibility is not good. I may rewrite it in the future (and add this feature).

**Comment by gilliginsisland** [comment]
Cool. Thanks for all the work you've put into this fork of grub, the addition of the mem and wimboot modules have been invaluable.

**Comment by steve6375** [comment]
Not compatible with old code. If bcd, bootmgr or bootmgfw is specified in wimboot list then it now fails to work.

**Comment by a1ive** [comment]
> Not compatible with older menus. If bcd or boot.sdi, is specified in wimboot list then it now fails to work.

It is compatible with older menus. 
`wimboot @:bootmgfw.efi:/wim/bootmgfw.efi @:bcd:/wim/bcd @:boot.sdi:/wim/boot.sdi @:boot.wim:/wim/winpe.wim` works for me.

**Comment by steve6375** [comment]
oh sorry - the files are no longer in wimboot.xz. My mistake!
