### ISSUE TITLE
stat -c is reporting some contiguous files as not contiguous

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#72]
Booting to grubfm.iso
UEFI grub2 does NOT have any problem - this issue is only for MBR\Legacy grub2

stat -c on some files on NTFS partition returns result as not-contiguous.

All files are contiguous in \_ISO\MAINMENU

grub4dos
![1](https://user-images.githubusercontent.com/1469350/89108693-5358c000-d432-11ea-8ee0-ef4bf9c1f074.jpg)

grubfm.iso
![20200801_135412](https://user-images.githubusercontent.com/1469350/89108696-5653b080-d432-11ea-864b-b5bad1af16e0.jpg)

Bug noticed in June 2020 and also current build.

**Comment by steve6375** [comment]
That seems to have fixed it, but latest build seems to be weird with Win10 Install ISOs (UEFI64)???
1. Under VBOX - very large screen resolution chosen by WInPE and no mouse or keyboard input working
2. start.bat and winpeshl.ini not in X:\windows\system32 and so not running even on real system

**Comment by a1ive** [comment]
> That seems to have fixed it, but latest build seems to be weird with Win10 Install ISOs (UEFI64)???
> 
> 1. Under VBOX - very large screen resolution chosen by WInPE and no mouse or keyboard input working

`wimboot --highest=no ...`
By default wimboot will enable this option in BCD.
![1](https://user-images.githubusercontent.com/10670106/89121789-a7c47400-d4f4-11ea-8261-62ec18c59ff7.png)

**Comment by a1ive** [comment]
> 2. start.bat and winpeshl.ini not in X:\windows\system32 and so not running even on real system

fixed in https://github.com/a1ive/grub/commit/01625ccdf4390f49eaab5a1302d8b12c85356a88
