### ISSUE TITLE
warning: your core.img is unusually large. It won't fit in the embedding area.

### ISSUE THREAD

**Issue by niemtin007** [a1ive/grub#74]
Hello Alive,

Thank you for your hard work in developing the Grub2 bootloader.

When I tried to install the last built of Grub2 for USB/HDD in legacy BIOS mode I met a warning & an error:
> warning: your core.img is unusually large.  It won't fit in the embedding area.
> error: embedding is not possible, but this is required for cross-disk install

![image](https://user-images.githubusercontent.com/12592676/91251588-f678cd00-e785-11ea-8cbd-7b9ed03e0614.png)

it seems that the legacy BIOS mode has reached its limited capacity and cannot add more new features!?

Could you help me to resolve this problem?

Thanks,

**Comment by steve6375** [comment]
Which version works?

**Comment by a1ive** [comment]
![1](https://user-images.githubusercontent.com/10670106/91285521-e67ddf00-e7bf-11ea-8221-3676ba34267e.png)

**Comment by steve6375** [comment]
Does it depend on where the partition starts? e.g. Sector 63 or sector 2048, etc?
Run `RMPrepUSB - Drive Info - 0`   to see partition details of the target drive.

**Comment by niemtin007** [comment]
> Which version works?
Older versions of a few months ago still work fine. I don't remember which one.

> Does it depend on where the partition starts? e.g. Sector 63 or sector 2048, etc?
> Run RMPrepUSB - Drive Info - 0 to see partition details of the target drive.
@steve6375 
Thank you for your answer.
When I change the "stating sector" from 63 to 2048 everything works fine now.

Can you explain to me why?

**Comment by steve6375** [comment]
I think some grub2 boot code is placed between MBR (LBA0) and start of first partition.
For compatibility, the code should fit in sectors 0-62 because typical older MBR disks have first partition at 63.
I guess that the grub2 boot code has 'grown' somehow?

**Comment by a1ive** [comment]
> I think some grub2 boot code is placed between MBR (LBA0) and start of first partition.
> For compatibility, the code should fit in sectors 0-62 because typical older MBR disks have first partition at 63.
> I guess that the grub2 boot code has 'grown' somehow?

yes.
