### ISSUE TITLE
Question: dd status=progress?

### ISSUE THREAD

**Issue by DapperDeer** [a1ive/grub#81]
Hi there,

I was wondering if there is an equivalent to `status=progress` for this dd? 
Or if it is possible to add it?

Thanks

**Comment by a1ive** [comment]
```
export enable_progress_indicator=1
dd --if=(hd0,1) --of=(hd0,2) bs=512
```

**Comment by DapperDeer** [comment]
Heya, 

dd isn't working for me and I'm really confused as to why. 

The commands that I've tried are:
`dd --if=(hd0) --seek=2048 --of=(hd0) --skip=88082432 -b 4096 -c 20479`
`dd --if=(hd0,msdos3) --of=(hd0,msdos1) -b 4096`
`dd --if=(hd0,3) --of=(hd0,1) -b 4096`

All three commands don't return anything and I have entered `export enable_progress_indicator=1` before trying any of the commands. The drive I'm trying to dd is NTFS and I've `insmod ntfs` and `insmod part_msdos`

Thanks

**Comment by steve6375** [comment]
MBR/legacy, uefi32 or uefi64 boot to grub2?

**Comment by DapperDeer** [comment]
MBR/Legacy

**Comment by steve6375** [comment]
Ok, 6 bytes works but 40gb does not. What about sizes in between?
E.g .1000 blocks of size 4096?

**Comment by DapperDeer** [comment]
` dd --if=(hd0) --seek=2048 --of=(hd0) --skip=88082432 -b 4096 -c 1000` worked.
![image](https://user-images.githubusercontent.com/24649585/97928630-4cd13180-1d1c-11eb-9571-a228d7ba841b.png)

**Comment by steve6375** [comment]
Well, I would start increasing -c until it started to fail.
You may find that when you get to a certain size it will fail.
e.g. -c 65536   
then it would point to a number\integer size issue.

**Comment by a1ive** [comment]
I think it's an overflow bug.
https://github.com/a1ive/grub/blob/4966126acb4ccdb4c4ca1db57d487e2786060ed4/grub-core/commands/dd.c#L88
