### ISSUE TITLE
menuentry --help-msg buggy

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub#89]
![image](https://user-images.githubusercontent.com/1469350/99971128-af09d900-2d94-11eb-8fc9-9b66ae670a88.png)
Same menu entry if move cursor up...
![image](https://user-images.githubusercontent.com/1469350/99971200-c47f0300-2d94-11eb-856f-ea5348b0948d.png)

![image](https://user-images.githubusercontent.com/1469350/99971304-e11b3b00-2d94-11eb-85c0-2fbb177c8282.png)
Sometimes parts missing
Sometimes no message.
Depends on up/down cursor selection - you get different results!
```
#a1ive grub file manager must be first menu entry (either keep as entry 0 or remove this entry)
if [ -d "(${bootdev},msdos1)/_ISO/MAINMENU" ] ; then 
	menuentry "a1ive grub2 File Manager (/_ISO/MAINMENUX)" --help-msg="qwertyasdfghjkl"  --class=dir {
		delvars
		grubfm "(${bootdev},msdos1)/_ISO/MAINMENU/"
	}
else
	menuentry "a1ive grub2 File Manager" --class=dir {
		delvars
		grubfm
	}
fi

if [ -f "${grubfm0}" ] ; then 
	menuentry "${grubfm0_title}" --class=exe --help-msg="0aaaaa bbbbb ccccc ddddd eeeee fffff" {
		set grubfm_file="${grubfm0}"
		if [ "${grubfm0_type}" = "wininst" ] ; then delvars; configfile (${user})/boot/grubfm/rules/iso/win.sh ; fi
		if [ "${grubfm0_type}" = "e2biso" ]  ; then delvars; configfile (${user})/boot/grubfm/rules/iso/e2b.sh ; fi
		delvars; grubfm_open "${grubfm_file}"
	}
fi

if [ -f "${grubfm1}" ] ; then 
	menuentry "${grubfm1_title}" --help-msg="bbbbbbbbbbb" --class=exe --help-msg="1aaaaa bbbbb ccccc ddddd eeeee fffff" {
		set grubfm_file="${grubfm1}"
		if [ "${grubfm1_type}" = "wininst" ] ; then delvars; configfile (${user})/boot/grubfm/rules/iso/win.sh ; fi
		if [ "${grubfm1_type}" = "e2biso" ]  ; then delvars; configfile (${user})/boot/grubfm/rules/iso/e2b.sh ; fi
		delvars; grubfm_open "${grubfm_file}"
	}
fi

if [ -f "${grubfm2}" ] ; then 
	menuentry "${grubfm2_title}" --help-msg="cccccccccc" --class=exe --help-msg="2aaaaa bbbbb ccccc ddddd eeeee fffff" {
		set grubfm_file="${grubfm2}"
		if [ "${grubfm2_type}" = "wininst" ] ; then delvars; configfile (${user})/boot/grubfm/rules/iso/win.sh ; fi
		if [ "${grubfm2_type}" = "e2biso" ]  ; then delvars; configfile (${user})/boot/grubfm/rules/iso/e2b.sh ; fi
		grubfm_open "${grubfm_file}"
	}
fi

if [ -f "${grubfm3}" ] ; then 
	menuentry "${grubfm3_title}" --class=exe --help-msg="3aaaaa bbbbb ccccc ddddd eeeee fffff" {
		set grubfm_file="${grubfm3}"
		if [ "${grubfm3_type}" = "wininst" ] ; then delvars; configfile (${user})/boot/grubfm/rules/iso/win.sh ; fi
		if [ "${grubfm3_type}" = "e2biso" ]  ; then delvars; configfile (${user})/boot/grubfm/rules/iso/e2b.sh ; fi
		delvars; grubfm_open "${grubfm_file}"
	}
fi

```

**Comment by a1ive** [comment]
I have rewritten this part of the code and now you can test it.
Text mode is not supported for now.

**Comment by a1ive** [comment]
now also available in text mode.
![深度截图_选择区域_20201222130618](https://user-images.githubusercontent.com/10670106/102851344-8a1d8a00-4456-11eb-854b-42dd9c4a08e4.png)

**Comment by steve6375** [comment]
Graphics mode seems to work OK now :-)
Small issues with text mode
The grub2 menu help text is not cleared
![image](https://user-images.githubusercontent.com/1469350/102880253-ee365300-4442-11eb-903f-d7f7258fd935.png)
also cursor is left on screen
![image](https://user-images.githubusercontent.com/1469350/102880329-0908c780-4443-11eb-903a-26b9326b477f.png)

**Comment by steve6375** [comment]
P.S. How to specify colour for help text in console mode?

**Comment by a1ive** [comment]
> The grub2 menu help text is not cleared
> also cursor is left on screen

now should be fixed.

> How to specify colour for help text in console mode?

color_normal

![深度截图_选择区域_20201222220835](https://user-images.githubusercontent.com/10670106/102896986-46e90880-44a2-11eb-83b8-f68e7ec1b709.png)

**Comment by steve6375** [comment]
OK - so must be same colour as heading.

**Comment by a1ive** [comment]
'--help-msg' still doesn't work.
this works.
```
+ vbox {
  left = 0%
  top = 0%
  + label {
    id = "__help__"
    color = "#ffffff"
  }
}
```
this doesn't work.
```
+ vbox {
  left = 35%
  top = 20%
  + label {
    id = "__help__"
    color = "#ffffff"
  }
```

**Comment by a1ive** [comment]
bug fixed.
![1](https://user-images.githubusercontent.com/10670106/103091371-ec30e780-462e-11eb-8158-d15be7c99556.gif)

**Comment by Tnctr-altay-24** [comment]
A1ive kralsın süper *****

**Comment by Tnctr-altay-24** [comment]
I congratulate you, master. If you accept, I have a suggestion. I think it would be more pleasant if it was done as in the picture.
![Grubfm](https://user-images.githubusercontent.com/72962883/103121176-05b44c80-468c-11eb-9f91-5eba74256e6f.JPG)
